upload to appsend

diff --git a/.github/workflows/build-android-app.yml b/.github/workflows/build-android-app.yml
--- a/.github/workflows/build-android-app.yml
+++ b/.github/workflows/build-android-app.yml
@@ -65,6 +65,9 @@ on:
       aab-artifact-name:
         description: "The artifact name of the AAB."
         value: ${{ jobs.build.outputs.aab-artifact-name }}
+      install-url:
+        description: "URL to install the built app."
+        value: ${{ jobs.build-ios.outputs.install-url }}
 
 jobs:
   build:
@@ -76,6 +79,7 @@ jobs:
     timeout-minutes: 60
     environment:
       name: ${{ inputs.environment }}
+      url: ${{ steps.upload-to-appsend.outputs.install_url }}
     outputs:
       version: ${{ steps.get-version-number.outputs.version }}
       # build-number: ${{ steps.update-build-number.outputs.build_number }}
@@ -85,6 +89,7 @@ jobs:
       aab-artifact-id: ${{ steps.upload-aab.outputs.artifact-id }}
       aab-artifact-url: ${{ steps.upload-aab.outputs.artifact-url }}
       aab-artifact-name: ${{ steps.get-aab-artifact-name.outputs.aab_artifact_name }}
+      install-url: ${{ steps.upload-to-appsend.outputs.install_url }}
     defaults:
       run:
         working-directory: apps/rn-app
@@ -243,3 +248,19 @@ jobs:
           name: ${{ steps.get-aab-artifact-name.outputs.aab_artifact_name }}
           path: |
             apps/rn-app/*.aab
+
+      - name: Upload to AppSend
+        id: upload-to-appsend
+        if: ${{ vars.SKIP_UPLOAD != 'true' }}
+        continue-on-error: true
+        run: |
+          result=$(curl --insecure https://api.appsend.dev/v1/uploads/ -F file=@"$(ls *.apk | head -n 1)") # we have encountered issues with the SSL certificate of this server on the GitHub Actions runner, therefore --insecure is used
+          echo $result | jq '.'
+          uid="$(echo $result | jq -r '.uid')"
+          if [ -z "$uid" ]; then
+            echo "[ERROR] Failed to upload to AppSend: $result"
+            exit 1
+          fi
+          install_url="https://appsend.dev/i/$uid"
+          echo "Download URL: $install_url"
+          echo "install_url=$install_url" >> $GITHUB_OUTPUT
diff --git a/.github/workflows/build-ios-app.yml b/.github/workflows/build-ios-app.yml
--- a/.github/workflows/build-ios-app.yml
+++ b/.github/workflows/build-ios-app.yml
@@ -68,6 +68,9 @@ on:
       testflight-upload-succeeded:
         description: "Whether the TestFlight upload succeeded."
         value: ${{ jobs.build-ios.outputs.testflight-upload-succeeded }}
+      install-url:
+        description: "URL to install the built app."
+        value: ${{ jobs.build-ios.outputs.install-url }}
 
 jobs:
   build-ios:
@@ -79,6 +82,7 @@ jobs:
     timeout-minutes: 60
     environment:
       name: ${{ inputs.environment }}
+      url: ${{ steps.upload-to-appsend.outputs.install_url }}
     outputs:
       version: ${{ steps.get-version-number.outputs.version }}
       build-number: ${{ steps.update-build-number.outputs.build_number }}
@@ -89,6 +93,7 @@ jobs:
       ipa-artifact-url: ${{ steps.upload-ipa.outputs.artifact-url }}
       ipa-artifact-name: ${{ steps.get-ipa-artifact-name.outputs.ipa_artifact_name }}
       testflight-upload-succeeded: ${{ steps.upload-to-testflight.outputs.testflight_upload_succeeded }}
+      install-url: ${{ steps.upload-to-appsend.outputs.install_url }}
     defaults:
       run:
         working-directory: apps/rn-app
@@ -283,3 +288,19 @@ jobs:
         run: |
           fastlane ios lane_upload_to_testflight
           echo "testflight_upload_succeeded=true" >> $GITHUB_OUTPUT
+
+      - name: Upload to AppSend
+        id: upload-to-appsend
+        if: ${{ vars.SKIP_UPLOAD != 'true' }}
+        continue-on-error: true
+        run: |
+          result=$(curl --insecure https://api.appsend.dev/v1/uploads/ -F file=@"$(ls *.ipa | head -n 1)") # we have encountered issues with the SSL certificate of this server on the GitHub Actions runner, therefore --insecure is used
+          echo $result | jq '.'
+          uid="$(echo $result | jq -r '.uid')"
+          if [ -z "$uid" ]; then
+            echo "[ERROR] Failed to upload to AppSend: $result"
+            exit 1
+          fi
+          install_url="https://appsend.dev/i/$uid"
+          echo "Download URL: $install_url"
+          echo "install_url=$install_url" >> $GITHUB_OUTPUT
